#+title: SwanEmacs 🦢
#+author: Anthony Le Cigne
#+options: num:nil

This is my Emacs configuration. It is part of my [[https://github.com/alecigne/dotfiles][dotfiles]] as a Git
submodule.

It uses John Wiegley's [[https://github.com/jwiegley/use-package][use-package]] to make things:

- Neatly organized :: Everything is grouped by package. I also use
  [[https://github.com/jdtsmith/outli][outli]] to organize code by sections.

- Readable :: =use-package= offers a large choice of expressive
  keywords.

- Self-installable :: All Emacs packages are downloaded automatically
  when I first start Emacs on a new environment.

  Thanks to =use-package='s =:vc= keyword, packages can even be
  fetched directly from source.

* Structure

- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early-init.el]] is loaded. It contains a few specific customizations
  that can take effect before the normal init process begins.

- =init.el= loads [[http://wikemacs.org/wiki/Package.el][package.el]], add a few tweaks to =use-package= and
  then loads my personal config files located in =./lisp/alc/=:

  + =alc-core.el= -- the core configuration, shared across all
    workflows.
  + =alc-tools.el= -- domain-specific tools and integrations.
  + =alc-org.el= -- my [[https://orgmode.org/][Org-mode]] config.
  + =alc-experimental.el= -- experimental and in-progress
    configuration.

* Preparing and testing

A complete configuration can be run along with its [[https://github.com/jorgenschaefer/emacs-buttercup][Buttercup]] test
suite (because why not) with:

#+begin_src sh
  just prepare
#+end_src

This starts Emacs in batch mode, loads =early-init.el= and the
complete =init.el=, and then runs the tests. Because it exercises the
real configuration, the command also installs any missing ELPA
packages and fetches missing =:vc= dependencies. A first run may
therefore require network access and take longer; subsequent runs
reuse the installed packages.

This is why the Just recipe isn't called =test= but =prepare=.

* Local configuration

I usually add a short configuration (=alc-local.el= -- not included on
any public branch) on each machine for local customizations. For
example, the =org-agenda-files= variable will mix different Org
projects that depend on the machine I am working on. This way, I can
separate Org projects at the file level but still mix tasks and events
in the agenda to get a clear picture of my day. I then filter
everything by context to avoid distraction.

* About literate Emacs configurations

I am not a fan of literate Emacs configurations (yeah, I hate
them). This one used to be such a "literate config" based on a network
of [[https://www.orgmode.org/][Org file]], but I switched for the sake of simplicity. [[https://github.com/alecigne/.emacs.d/tree/faa6d3727074f9fce746fb9653a9b4242eedce6e][Browse the
last commit]] of that Org config if you're interested, or check the
+way too+ numerous literate configs out there.
